# Stage 1: Build stage
FROM node:24.10.0-alpine3.22 AS build-stage

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

# Stage 2: Production stage  
FROM nginx:1.29.1-alpine

COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY public/config.js /usr/share/nginx/html/config.js

EXPOSE 80