# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc

from . import comments_pb2 as comments__pb2

GRPC_GENERATED_VERSION = "1.75.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in comments_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class CommentsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateComment = channel.unary_unary(
            "/comments.CommentsService/CreateComment",
            request_serializer=comments__pb2.CreateCommentRequest.SerializeToString,
            response_deserializer=comments__pb2.CreateCommentResponse.FromString,
            _registered_method=True,
        )
        self.GetAllComments = channel.unary_unary(
            "/comments.CommentsService/GetAllComments",
            request_serializer=comments__pb2.GetAllCommentsRequest.SerializeToString,
            response_deserializer=comments__pb2.GetAllCommentsResponse.FromString,
            _registered_method=True,
        )
        self.GetComment = channel.unary_unary(
            "/comments.CommentsService/GetComment",
            request_serializer=comments__pb2.GetCommentRequest.SerializeToString,
            response_deserializer=comments__pb2.GetCommentResponse.FromString,
            _registered_method=True,
        )
        self.GetCommentsByProjectId = channel.unary_unary(
            "/comments.CommentsService/GetCommentsByProjectId",
            request_serializer=comments__pb2.GetCommentsByProjectIdRequest.SerializeToString,
            response_deserializer=comments__pb2.GetCommentsByProjectIdResponse.FromString,
            _registered_method=True,
        )
        self.GetCommentsByAuthorId = channel.unary_unary(
            "/comments.CommentsService/GetCommentsByAuthorId",
            request_serializer=comments__pb2.GetCommentsByAuthorIdRequest.SerializeToString,
            response_deserializer=comments__pb2.GetCommentsByAuthorIdResponse.FromString,
            _registered_method=True,
        )
        self.UpdateComment = channel.unary_unary(
            "/comments.CommentsService/UpdateComment",
            request_serializer=comments__pb2.UpdateCommentRequest.SerializeToString,
            response_deserializer=comments__pb2.UpdateCommentResponse.FromString,
            _registered_method=True,
        )
        self.DeleteComment = channel.unary_unary(
            "/comments.CommentsService/DeleteComment",
            request_serializer=comments__pb2.DeleteCommentRequest.SerializeToString,
            response_deserializer=comments__pb2.DeleteCommentResponse.FromString,
            _registered_method=True,
        )


class CommentsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetAllComments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetCommentsByProjectId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetCommentsByAuthorId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CommentsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateComment": grpc.unary_unary_rpc_method_handler(
            servicer.CreateComment,
            request_deserializer=comments__pb2.CreateCommentRequest.FromString,
            response_serializer=comments__pb2.CreateCommentResponse.SerializeToString,
        ),
        "GetAllComments": grpc.unary_unary_rpc_method_handler(
            servicer.GetAllComments,
            request_deserializer=comments__pb2.GetAllCommentsRequest.FromString,
            response_serializer=comments__pb2.GetAllCommentsResponse.SerializeToString,
        ),
        "GetComment": grpc.unary_unary_rpc_method_handler(
            servicer.GetComment,
            request_deserializer=comments__pb2.GetCommentRequest.FromString,
            response_serializer=comments__pb2.GetCommentResponse.SerializeToString,
        ),
        "GetCommentsByProjectId": grpc.unary_unary_rpc_method_handler(
            servicer.GetCommentsByProjectId,
            request_deserializer=comments__pb2.GetCommentsByProjectIdRequest.FromString,
            response_serializer=comments__pb2.GetCommentsByProjectIdResponse.SerializeToString,
        ),
        "GetCommentsByAuthorId": grpc.unary_unary_rpc_method_handler(
            servicer.GetCommentsByAuthorId,
            request_deserializer=comments__pb2.GetCommentsByAuthorIdRequest.FromString,
            response_serializer=comments__pb2.GetCommentsByAuthorIdResponse.SerializeToString,
        ),
        "UpdateComment": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateComment,
            request_deserializer=comments__pb2.UpdateCommentRequest.FromString,
            response_serializer=comments__pb2.UpdateCommentResponse.SerializeToString,
        ),
        "DeleteComment": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteComment,
            request_deserializer=comments__pb2.DeleteCommentRequest.FromString,
            response_serializer=comments__pb2.DeleteCommentResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "comments.CommentsService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "comments.CommentsService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class CommentsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateComment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/comments.CommentsService/CreateComment",
            comments__pb2.CreateCommentRequest.SerializeToString,
            comments__pb2.CreateCommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetAllComments(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/comments.CommentsService/GetAllComments",
            comments__pb2.GetAllCommentsRequest.SerializeToString,
            comments__pb2.GetAllCommentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetComment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/comments.CommentsService/GetComment",
            comments__pb2.GetCommentRequest.SerializeToString,
            comments__pb2.GetCommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetCommentsByProjectId(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/comments.CommentsService/GetCommentsByProjectId",
            comments__pb2.GetCommentsByProjectIdRequest.SerializeToString,
            comments__pb2.GetCommentsByProjectIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetCommentsByAuthorId(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/comments.CommentsService/GetCommentsByAuthorId",
            comments__pb2.GetCommentsByAuthorIdRequest.SerializeToString,
            comments__pb2.GetCommentsByAuthorIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateComment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/comments.CommentsService/UpdateComment",
            comments__pb2.UpdateCommentRequest.SerializeToString,
            comments__pb2.UpdateCommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteComment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/comments.CommentsService/DeleteComment",
            comments__pb2.DeleteCommentRequest.SerializeToString,
            comments__pb2.DeleteCommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
