# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

from . import content_pb2 as content__pb2
import grpc

GRPC_GENERATED_VERSION = "1.75.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in content_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ContentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.

        """
        self.GetAbout = channel.unary_unary(
            "/content.ContentService/GetAbout",
            request_serializer=content__pb2.AboutRequest.SerializeToString,
            response_deserializer=content__pb2.AboutResponse.FromString,
            _registered_method=True,
        )
        self.GetTech = channel.unary_unary(
            "/content.ContentService/GetTech",
            request_serializer=content__pb2.TechRequest.SerializeToString,
            response_deserializer=content__pb2.TechResponse.FromString,
            _registered_method=True,
        )
        self.GetProjects = channel.unary_unary(
            "/content.ContentService/GetProjects",
            request_serializer=content__pb2.ProjectsRequest.SerializeToString,
            response_deserializer=content__pb2.ProjectsResponse.FromString,
            _registered_method=True,
        )
        self.GetCertificates = channel.unary_unary(
            "/content.ContentService/GetCertificates",
            request_serializer=content__pb2.CertificatesRequest.SerializeToString,
            response_deserializer=content__pb2.CertificatesResponse.FromString,
            _registered_method=True,
        )
        self.GetPublications = channel.unary_unary(
            "/content.ContentService/GetPublications",
            request_serializer=content__pb2.PublicationsRequest.SerializeToString,
            response_deserializer=content__pb2.PublicationsResponse.FromString,
            _registered_method=True,
        )


class ContentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAbout(self, request, context):
        """About"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTech(self, request, context):
        """Tech"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetProjects(self, request, context):
        """Projects"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetCertificates(self, request, context):
        """Certificates"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPublications(self, request, context):
        """Publications"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ContentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetAbout": grpc.unary_unary_rpc_method_handler(
            servicer.GetAbout,
            request_deserializer=content__pb2.AboutRequest.FromString,
            response_serializer=content__pb2.AboutResponse.SerializeToString,
        ),
        "GetTech": grpc.unary_unary_rpc_method_handler(
            servicer.GetTech,
            request_deserializer=content__pb2.TechRequest.FromString,
            response_serializer=content__pb2.TechResponse.SerializeToString,
        ),
        "GetProjects": grpc.unary_unary_rpc_method_handler(
            servicer.GetProjects,
            request_deserializer=content__pb2.ProjectsRequest.FromString,
            response_serializer=content__pb2.ProjectsResponse.SerializeToString,
        ),
        "GetCertificates": grpc.unary_unary_rpc_method_handler(
            servicer.GetCertificates,
            request_deserializer=content__pb2.CertificatesRequest.FromString,
            response_serializer=content__pb2.CertificatesResponse.SerializeToString,
        ),
        "GetPublications": grpc.unary_unary_rpc_method_handler(
            servicer.GetPublications,
            request_deserializer=content__pb2.PublicationsRequest.FromString,
            response_serializer=content__pb2.PublicationsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "content.ContentService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "content.ContentService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class ContentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAbout(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/content.ContentService/GetAbout",
            content__pb2.AboutRequest.SerializeToString,
            content__pb2.AboutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTech(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/content.ContentService/GetTech",
            content__pb2.TechRequest.SerializeToString,
            content__pb2.TechResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetProjects(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/content.ContentService/GetProjects",
            content__pb2.ProjectsRequest.SerializeToString,
            content__pb2.ProjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetCertificates(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/content.ContentService/GetCertificates",
            content__pb2.CertificatesRequest.SerializeToString,
            content__pb2.CertificatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetPublications(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/content.ContentService/GetPublications",
            content__pb2.PublicationsRequest.SerializeToString,
            content__pb2.PublicationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
