"""Cascade deletion

Revision ID: 08aa32224a8f
Revises: e8b30e350263
Create Date: 2025-09-24 13:51:56.352542

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08aa32224a8f"
down_revision: Union[str, Sequence[str], None] = "e8b30e350263"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("comments_parent_comment_id_fkey"), "comments", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "comments",
        "comments",
        ["parent_comment_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.create_foreign_key(
        op.f("comments_parent_comment_id_fkey"),
        "comments",
        "comments",
        ["parent_comment_id"],
        ["id"],
    )
    # ### end Alembic commands ###
